---
abstract: 'Net::Twitch::Oauth2 wrapper for Twitch.tv OAuth2'
author:
  - 'Ronald Reed <rjreed67@gmail.com>'
build_requires:
  LWP::UserAgent: '0'
  Test::More: '0.10'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Twitch-Oauth2
provides:
  Net::Twitch::Oauth2:
    file: lib/Net/Twitch/Oauth2.pm
    version: '0.03'
resources:
  license: http://dev.perl.org/licenses/
version: '0.03'
